"""empty message

Revision ID: 066ad9258a82
Revises: 999fe3ffc69e
Create Date: 2020-08-05 17:22:08.463953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '066ad9258a82'
down_revision = '999fe3ffc69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid_details', 'created_at')
    op.drop_column('bids', 'created_at')
    op.drop_column('items', 'auction_end')
    op.drop_column('items', 'created_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'auction_end')
    op.drop_column('bids', 'created_at')
    op.drop_column('bid_details', 'created_at')
    # ### end Alembic commands ###
