"""empty message

Revision ID: 097dfcd05240
Revises: 7e148984abaf
Create Date: 2020-07-23 10:55:36.308652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097dfcd05240'
down_revision = '7e148984abaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('donor_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'donor_email')
    # ### end Alembic commands ###
