"""empty message

Revision ID: 73dfd6939738
Revises: 8a124d1f7b37
Create Date: 2020-07-22 12:02:48.974439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73dfd6939738'
down_revision = '8a124d1f7b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bids', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.drop_column('bids', 'item_id')
    # ### end Alembic commands ###
