"""empty message

Revision ID: 7e148984abaf
Revises: 73dfd6939738
Create Date: 2020-07-22 19:42:58.086283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e148984abaf'
down_revision = '73dfd6939738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('charity_score', sa.String(), nullable=True))
    op.add_column('items', sa.Column('charity_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'charity_url')
    op.drop_column('items', 'charity_score')
    # ### end Alembic commands ###
