"""empty message

Revision ID: 995a9519c95d
Revises: 097dfcd05240
Create Date: 2020-07-28 10:33:26.748735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995a9519c95d'
down_revision = '097dfcd05240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('charity_score_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'charity_score_image')
    # ### end Alembic commands ###
