"""empty message

Revision ID: 999fe3ffc69e
Revises: edb25fcc9ef4
Create Date: 2020-08-04 17:09:51.310909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '999fe3ffc69e'
down_revision = 'edb25fcc9ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('receipt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('finals')
    op.add_column('bids', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('bids', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('bids', sa.Column('winner', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'bids', 'users', ['user_id'], ['id'])
    op.drop_column('bids', 'bidder_email')
    op.drop_column('bids', 'bidder_name')
    op.add_column('items', sa.Column('auction_end', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('auction_length', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'])
    op.drop_column('items', 'donor_email')
    op.drop_column('items', 'bidding_time')
    op.drop_column('items', 'donor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('donor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('bidding_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('donor_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'user_id')
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'auction_length')
    op.drop_column('items', 'auction_end')
    op.add_column('bids', sa.Column('bidder_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bids', sa.Column('bidder_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.drop_column('bids', 'winner')
    op.drop_column('bids', 'user_id')
    op.drop_column('bids', 'created_at')
    op.create_table('finals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('street_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receipt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='finals_pkey')
    )
    op.drop_table('bid_details')
    op.drop_table('users')
    # ### end Alembic commands ###
