"""empty message

Revision ID: 9fbbf340b3bc
Revises:
Create Date: 2020-07-18 13:09:53.395353

 """
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9fbbf340b3bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('donor', sa.String(), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
