"""empty message

Revision ID: b793822e98ea
Revises: 9fbbf340b3bc
Create Date: 2020-07-20 15:55:44.210689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b793822e98ea'
down_revision = '9fbbf340b3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(), nullable=True))
    op.add_column('items', sa.Column('charity', sa.String(), nullable=True))
    op.add_column('items', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image')
    op.drop_column('items', 'charity')
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
