"""empty message

Revision ID: c278fa71221a
Revises: 066ad9258a82
Create Date: 2020-08-05 17:43:47.393071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c278fa71221a'
down_revision = '066ad9258a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid_details', sa.Column('created_at', sa.BigInteger(), nullable=True))
    op.add_column('bids', sa.Column('created_at', sa.BigInteger(), nullable=True))
    op.add_column('items', sa.Column('auction_end', sa.BigInteger(), nullable=True))
    op.add_column('items', sa.Column('created_at', sa.BigInteger(), nullable=True))
    op.drop_column('items', 'charity_score')
    op.add_column('users', sa.Column('created_at', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('items', 'charity_score')
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'auction_end')
    op.drop_column('bids', 'created_at')
    op.drop_column('bid_details', 'created_at')
    # ### end Alembic commands ###
